### ISSUE TITLE
Joris papers

### ISSUE THREAD

**Issue by stanislas-brossette** [jrl-umi3218/jrl-umi3218.github.com#2]
Need to upload Joris's papers (pre-IEEE versions) on HAL or other in order to put the links to the pdf and bib in the website.

**Comment by gergondet** [comment]
I am guessing this was fixed by https://github.com/jrl-umi3218/jrl-umi3218.github.com/commit/5f4f9522f2dfd62e0d12cfbc78eb5a54e4b3e760?

**Comment by stanislas-brossette** [comment]
I can't deposit Joris Humanoid as I don't has the pre-IEEE version
1) Si vous avez l'autorisation de l'éditeur de déposer votre texte avec sa mise en page, veuillez cocher l'option correspondante à l'étape du dépôt de fichier (voir la documentation : https://hal.archives-ouvertes.fr/page/telechargement-des-fichiers#informations) . A défaut, merci de déposer le fichier auteur(=sans mise en page éditeur) 2) les actes sont publiés cf. DOI). Merci de modifier en actes OUI et compléter le champ source

**Comment by haudren** [comment]
Just to comment, it is probably on rob-dev or gite, but I don't think I have access to the project. Maybe @gergondet can check if it exists somewhere ?

**Comment by stanislas-brossette** [comment]
Fixed for the Humanoids. But got the same problem with the AURO.
I uploaded the version from the repo git@rob-dev.lirmm.fr:kheddar/auro-2015.git 
But it does not seem to be the final version.

**Comment by aescande** [comment]
This issue is outdated.
