### ISSUE TITLE
favicon.ico not found on local test

### ISSUE THREAD

**Issue by GuicarMIS** [jrl-umi3218/jrl-umi3218.github.com#51]
When testing locally the website, a warning occurs when running the recommended command "bundle exec jekyll server --safe --trace":
/home/guillaume/gems/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
 
And then, when loading the website in a browser the following appears in the shell:
[2021-12-09 18:02:57] ERROR `/favicon.ico' not found

No webpage appears. 

By removing the --safe argument, no warning, no error happens and the website can be tested. 

I am using Xubuntu 20.04 with a fresh install of the tools recommended in the readme of the website.

**Comment by aescande** [comment]
I encountered the same problem as well and could use the same fix.
I added the workaround with the `--safe` in the readme (9b6b08d).

There should be a way to fix the error at the source by investigating the deprecation warning, but I don't have the combo competence+time to look at this so the workaround will do for now (maybe @gergondet would have an idea).

**Comment by gergondet** [comment]
I think it's ok to remove the `--safe` in general.

In fact, the [doc](https://jekyllrb.com/docs/configuration/options/) says it does the following:
```
Disable [non-whitelisted plugins](https://jekyllrb.com/docs/plugins/), caching to disk, and ignore symbolic links.
```

So I'm not sure how it interferes with the favicon but it's ok not to use it imho
