### ISSUE TITLE
Fix htmlproofer >= 3.0 issue

### ISSUE THREAD

**Issue by gergondet** [jrl-umi3218/jrl-umi3218.github.com#9]
On travis, builds with html-proofer >= 3.0 are currently broken. I have not been able to reproduce the issue locally and I lack the ruby ecosystem's knowledge to understand and fix this issue on travis.

Therefore, I have forced the version to be < 3.0 for CI on the master branch. I've setup a CI branch that uses the latest html-proofer version. We should check on it once in a while to see if this build. If someone has the time to figure out this issue, feel free to toy with this branch...

**Comment by haudren** [comment]
I am pretty dumbfounded: it seems that html proofer cannot find its own Utils module. But on my machine, there is absolutely no problem and ruby/gem versions are similar. If I get another idea, I'll come back here.

**Comment by gergondet** [comment]
So... swtiching to the container-based infrastructure solved the issue...
